### PR TITLE
[RX-TEAM 6048] Rm stats for faster loading

### PR DESCRIPTION
**Pull request by ebarojas**
Rm unnecessary queries to speed up load time

### CODE REVIEW

**Comment by ebarojas** [comment]
There are three heavy queries that are performed with Cron Jobs, once this PR is merged and promoted, we'll remove those jobs to avoid unnecessary strain in the dbase.

**Comment by JasonBerto** [comment]
LGTM:

image

**Comment by JasonBerto** [comment]
Qa done, no puedo cambiar los labels

**Review by mevangelista-alvarado — APPROVED** [review]
LGTM!

**Pull request merged**
